[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ErrorCorrector"
version = "0.1.0"
description = "ErrorCorrector"
authors = [{name = "Mineev Ivan", email = "mineeeevich@gmail.com"}]
dependencies = [
    "torch",
    "torchvision",
    "pandas",
    "scikit-learn",
    "tqdm",
    "matplotlib",
    "seaborn",
    "plotly",
    "xgboost",
    "mlflow",
    "python-dotenv",
    "umap-learn"
]

[tool.setuptools]

[tool.setuptools.packages.find]
where = ["."]
include = ["src*"]
